import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import { open, save } from "@tauri-apps/plugin-dialog";
import type { Batch, Carton, CartonProduct, Grade, PhotoInput, RecordRow } from "./types";

const emptyBatch = {
  batchNo: `QA-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}`,
  inspectionDate: new Date().toISOString().slice(0, 10)
};

function App() {
  const [batches, setBatches] = useState<Batch[]>([]);
  const [batch, setBatch] = useState<Batch | null>(null);
  const [cartons, setCartons] = useState<Carton[]>([]);
  const [carton, setCarton] = useState<Carton | null>(null);
  const [records, setRecords] = useState<RecordRow[]>([]);
  const [products, setProducts] = useState<CartonProduct[]>([]);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [showBatch, setShowBatch] = useState(false);
  const [showReport, setShowReport] = useState(false);
  const [deleteMode, setDeleteMode] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<Batch|null>(null);
  const [cartonPage, setCartonPage] = useState(1);
  const cartonPageSize = 70;
  const cartonPageCount = Math.max(1, Math.ceil(cartons.length / cartonPageSize));
  const visibleCartons = cartons.slice((cartonPage - 1) * cartonPageSize, cartonPage * cartonPageSize);

  const showError = (e: unknown) => setMessage(String(e));
  const refreshBatches = async () => setBatches(await api.listBatches());
  const refreshBatch = async (selected = batch) => {
    if (!selected) return;
    const cs = await api.listCartons(selected.id); setCartons(cs);
    const current = carton ? cs.find(c => c.id === carton.id) ?? null : null; setCarton(current);
    if (!current) {
      setRecords([]);
      setProducts([]);
      return;
    }
    const [nextRecords, nextProducts] = await Promise.all([
      api.listRecords(selected.id, current.id),
      api.listCartonProducts(current.id)
    ]);
    setRecords(nextRecords);
    setProducts(nextProducts);
  };
  useEffect(() => { refreshBatches().catch(showError).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (batch) refreshBatch(batch).catch(showError); }, [batch?.id]);
  useEffect(() => { setCartonPage(1); }, [batch?.id]);
  useEffect(() => { if (cartonPage > cartonPageCount) setCartonPage(cartonPageCount); }, [cartonPage, cartonPageCount]);

  if (!batch) return <div className="app"><header><div><h1>Clothing Quality Inspection</h1><p>Offline inspection and Excel export</p></div><div className="header-actions"><button className={deleteMode?'danger active-delete':''} onClick={()=>setDeleteMode(value=>!value)}>{deleteMode?'Done':'Delete Batches'}</button><button className="primary" onClick={() => setShowBatch(true)}>New Batch</button></div></header>
    {message && <Notice text={message} close={() => setMessage("")} />}
    <main className="batch-grid">{loading?<div className="empty">Loading local data…</div>:<>{batches.map(b => <div className="batch-card-wrap" key={b.id}><button className="batch-card" onClick={() => {if(!deleteMode)setBatch(b)}}><strong>{b.batchNo}</strong><span>{b.inspectionDate}</span></button>{deleteMode&&<button className="batch-delete-x" title={`Delete batch ${b.batchNo}`} aria-label={`Delete batch ${b.batchNo}`} onClick={()=>setDeleteTarget(b)}>×</button>}</div>)}{!batches.length && <div className="empty">No inspection batches yet. Create one to begin.</div>}</>}</main>
    {showBatch && <BatchDialog close={() => setShowBatch(false)} save={async input => { await api.createBatch(input); setShowBatch(false); await refreshBatches(); }} />}
    {deleteTarget&&<DeleteBatchDialog batch={deleteTarget} close={()=>setDeleteTarget(null)} remove={async()=>{await api.deleteBatch(deleteTarget.id);setDeleteTarget(null);await refreshBatches();setMessage(`Batch ${deleteTarget.batchNo} deleted`);}}/>}
  </div>;

  return <div className="app"><header><div><button className="back" onClick={() => { setBatch(null); setCarton(null); setProducts([]); }}>← Batch List</button><h1>{batch.batchNo}</h1><p>{batch.inspectionDate}</p></div><div className="header-actions"><button onClick={() => setShowReport(true)}>View Report</button><button onClick={async()=>{const path=await save({defaultPath:'p.xlsx',filters:[{name:'Excel File',extensions:['xlsx']}],title:'Save p.xlsx Import Template'});if(!path)return;try{const savedPath=await api.exportCartonTemplate(path);setMessage(`Template exported: ${savedPath}`);}catch(e){showError(e);}}}>Export Template</button><button onClick={async()=>{const path=await open({multiple:false,filters:[{name:'p.xlsx Format',extensions:['xlsx']}],title:'Import Cartons and UPC Details from p.xlsx'});if(!path)return;try{const result=await api.importCartons(batch.id,path);await refreshBatch(batch);setMessage(`Imported ${result.imported} cartons and ${result.products} UPCs: ${result.created} created, ${result.updated} updated`);}catch(e){showError(e);}}}>Import Cartons</button><button onClick={() => exportData(batch.id).catch(showError)}>Export Excel</button><button className="primary" onClick={() => (document.getElementById("new-carton") as HTMLDialogElement)?.showModal()}>Add Carton</button></div></header>
    {message && <Notice text={message} close={() => setMessage("")} />}
    <div className="workspace"><aside className="carton-sidebar"><h2>Cartons</h2><div className="carton-grid">{visibleCartons.map(c => <button key={c.id} title={`Carton ${c.cartonNo}${c.inspectedQty>0?` · Recorded ${c.inspectedQty}`:' · Not recorded'}${c.status==='completed'?' · Completed':''}`} aria-label={`Carton ${c.cartonNo}`} className={`carton-square ${c.inspectedQty>0?'has-records':'empty-carton'} ${carton?.id === c.id ? "active" : ""}`} onClick={async () => { setCarton(c); const [nextRecords,nextProducts]=await Promise.all([api.listRecords(batch.id,c.id),api.listCartonProducts(c.id)]);setRecords(nextRecords);setProducts(nextProducts); }}><span>{c.cartonNo}</span>{c.status==='completed'&&<i aria-hidden="true">✓</i>}</button>)}</div>{!cartons.length&&<p className="carton-empty">No cartons</p>}{cartonPageCount>1&&<nav className="carton-pagination" aria-label="Carton pagination"><button disabled={cartonPage===1} onClick={()=>setCartonPage(page=>page-1)}>‹</button><span>{cartonPage} / {cartonPageCount}</span><button disabled={cartonPage===cartonPageCount} onClick={()=>setCartonPage(page=>page+1)}>›</button></nav>}</aside>
      <main className="content">{carton ? <CartonView batch={batch} carton={carton} products={products} records={records} refresh={() => refreshBatch()} notify={setMessage} /> : <div className="empty">Select a carton on the left to begin inspection.</div>}</main></div>
    <CartonDialog batchId={batch.id} saved={() => refreshBatch()} />
    {showReport && <ReportDialog batch={batch} cartons={cartons} close={()=>setShowReport(false)}/>}
  </div>;
}

type DraftRow = { id:number; recordId?:number; barcode:string; quantity:number; exceptionReason:string; photos:PhotoInput[] };
const newDraft = ():DraftRow => ({id:Date.now()+Math.random(),barcode:'',quantity:1,exceptionReason:'',photos:[]});

function CartonView({batch, carton, products, records, refresh, notify}:{batch:Batch; carton:Carton; products:CartonProduct[]; records:RecordRow[]; refresh:()=>Promise<void>; notify:(v:string)=>void}) {
  const [drafts,setDrafts]=useState<Record<Grade,DraftRow[]>>({A:[newDraft()],B:[newDraft()],C:[newDraft()],D:[newDraft()]});
  const [editingExisting,setEditingExisting]=useState(false);
  const [selectedUpc,setSelectedUpc]=useState<string|null>(null);
  const stats = useMemo(() => ([['A',carton.gradeA],['B',carton.gradeB],['C',carton.gradeC],['D',carton.gradeD]]), [carton]);
  useEffect(()=>setSelectedUpc(null),[carton.id]);
  const selectedProduct=products.find(product=>product.upc===selectedUpc)??null;
  const visibleRecords=selectedUpc?records.filter(record=>record.barcode===selectedUpc):records;
  const update=(grade:Grade,id:number,patch:Partial<DraftRow>)=>setDrafts(v=>({...v,[grade]:v[grade].map(row=>row.id===id?{...row,...patch}:row)}));
  const add=(grade:Grade)=>setDrafts(v=>({...v,[grade]:[...v[grade],newDraft()]}));
  const remove=(grade:Grade,id:number)=>setDrafts(v=>({...v,[grade]:v[grade].length===1?[newDraft()]:v[grade].filter(row=>row.id!==id)}));
  const addPhotoInputs=(grade:Grade,id:number,photos:PhotoInput[])=>setDrafts(current=>{const row=current[grade].find(r=>r.id===id);if(!row)return current;if(row.photos.length+photos.length>3){notify('Maximum 3 images per row');return current;}return {...current,[grade]:current[grade].map(item=>item.id===id?{...item,photos:[...item.photos,...photos]}:item)};});
  const addPhotos=async(grade:Grade,id:number,files:File[])=>{const valid=files.filter(f=>['image/jpeg','image/png'].includes(f.type));if(valid.length!==files.length){notify('Only JPG, JPEG, and PNG images are supported');return;}const photos=await Promise.all(valid.map(async f=>({name:f.name,dataBase64:(await fileData(f)).split(',')[1]})));addPhotoInputs(grade,id,photos);};
  const active=(["A","B","C","D"] as Grade[]).flatMap(grade=>drafts[grade].filter(r=>r.barcode.trim()||r.exceptionReason.trim()||r.photos.length).map(row=>({grade,row})));
  const beginEdit=()=>{const grouped=Object.fromEntries((["A","B","C","D"] as Grade[]).map(grade=>{const rows=records.filter(record=>record.grade===grade).map(record=>({id:Date.now()+Math.random(),recordId:record.id,barcode:record.barcode,quantity:record.quantity,exceptionReason:record.exceptionReason,photos:[]}));return [grade,rows.length?rows:[newDraft()]];})) as Record<Grade,DraftRow[]>;setDrafts(grouped);setEditingExisting(true);requestAnimationFrame(()=>document.querySelector('.entry')?.scrollIntoView({behavior:'smooth',block:'start'}));};
  const cancelEdit=()=>{setDrafts({A:[newDraft()],B:[newDraft()],C:[newDraft()],D:[newDraft()]});setEditingExisting(false);};
  const saveAll=async()=>{if(carton.status==='completed'){notify('This carton is complete. Click Reopen before editing');return;}if(!active.length&&!editingExisting){notify('Enter a product barcode first');return;}if(active.some(x=>!x.row.barcode.trim())){notify('Every row must include a product barcode');return;}if(active.some(x=>!Number.isInteger(x.row.quantity)||x.row.quantity<1)){notify('Quantity must be a positive integer');return;}try{if(editingExisting){await api.replaceCartonRecords({batchId:batch.id,cartonId:carton.id,records:active.map(({grade,row})=>({id:row.recordId,barcode:row.barcode.trim(),grade,quantity:row.quantity,exceptionReason:row.exceptionReason.trim(),photos:row.photos}))});}else{for(const {grade,row} of active){await api.createRecord({batchId:batch.id,cartonId:carton.id,barcode:row.barcode.trim(),grade,quantity:row.quantity,exceptionReason:row.exceptionReason.trim(),photos:row.photos});}}setDrafts({A:[newDraft()],B:[newDraft()],C:[newDraft()],D:[newDraft()]});setEditingExisting(false);await refresh();notify(editingExisting?'Carton changes saved':'Saved successfully');}catch(e){notify(String(e));}};
  const difference=carton.referenceQty===null?null:carton.inspectedQty-carton.referenceQty;
  return <><section className="summary product-summary"><div><h2>Carton {carton.cartonNo}</h2><p>Reference {carton.referenceQty??'None'} · Inspected {carton.inspectedQty} · Packed {carton.sealedQty}</p></div><div className="upc-list">{products.map(product=><button key={product.id} className={selectedUpc===product.upc?'active':''} onClick={()=>setSelectedUpc(current=>current===product.upc?null:product.upc)}><strong>{product.upc}</strong><span>: {product.unitsPerCarton}</span></button>)}{!products.length&&<span className="no-product">No imported UPCs for this carton</span>}</div></section>
    {selectedProduct&&<section className="product-detail"><div><span>UPC</span><strong>{selectedProduct.upc}</strong></div><div><span>Item No.</span><strong>{selectedProduct.itemNo||'—'}</strong></div><div><span>COLOR NAME</span><strong>{selectedProduct.colorName||'—'}</strong></div><div><span>COLOR#</span><strong>{selectedProduct.colorNo||'—'}</strong></div><div><span>MERCHANDISE DESCRIPTION</span><strong>{selectedProduct.description||'—'}</strong></div><div><span>SIZE or DIMENSION</span><strong>{selectedProduct.sizeDimension||'—'}</strong></div><div><span># OF CRTN</span><strong>{selectedProduct.cartonCount??'—'}</strong></div><div><span># OF UNITS PER CRTN</span><strong>{selectedProduct.unitsPerCarton}</strong></div><div><span>TOTAL UNITS</span><strong>{selectedProduct.totalUnits??'—'}</strong></div></section>}
    {carton.status!=='completed'&&<section className="entry"><div className="section-title"><h3>{editingExisting?'Edit Carton Records':'Inspection Entry'}</h3>{editingExisting&&<button onClick={cancelEdit}>Cancel Editing</button>}</div>{(["A","B","C","D"] as Grade[]).map(grade=><GradePanel key={grade} grade={grade} rows={drafts[grade]} add={()=>add(grade)} remove={id=>remove(grade,id)} update={(id,p)=>update(grade,id,p)} addPhotos={(id,files)=>addPhotos(grade,id,files)}/>)}<button className="primary save" onClick={saveAll}>{editingExisting?'Save Carton Changes':'Save All Rows'}</button></section>}
    <section className="records-layout"><div className="records"><div className="section-title"><h3>{selectedUpc?`Records for UPC ${selectedUpc}`:'Carton Records'}</h3><div className="record-actions">{carton.status!=='completed'&&<button disabled={!records.length||editingExisting} onClick={beginEdit}>Edit Carton</button>}{carton.status==='completed'?<button onClick={async()=>{try{await api.reopenCarton(carton.id);await refresh();notify('Carton reopened for editing');}catch(e){notify(String(e));}}}>Reopen</button>:<button disabled={!records.length||editingExisting} onClick={async()=>{const reference=carton.referenceQty===null?'None':String(carton.referenceQty);const diff=difference===null?'No reference':difference===0?'Matched':difference>0?`Over ${difference}`:`Short ${Math.abs(difference)}`;if(!confirm(`Actual inspected: ${carton.inspectedQty}\nReference quantity: ${reference}\nDifference: ${diff}\nA/B/C/D: ${carton.gradeA}/${carton.gradeB}/${carton.gradeC}/${carton.gradeD}\nPacked quantity: ${carton.sealedQty}\n\nComplete this carton?`))return;try{await api.completeCarton(carton.id);await refresh();notify('Carton completed');}catch(e){notify(String(e));}}}>Complete Carton</button>}</div></div><table><thead><tr><th>No.</th><th>Product Barcode</th><th>Grade</th><th>Quantity</th><th>Exception Reason</th></tr></thead><tbody>{visibleRecords.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.barcode}</td><td><span className={`grade g${r.grade}`}>{r.grade}</span></td><td>{r.quantity}</td><td>{r.exceptionReason||'—'}</td></tr>)}</tbody></table>{selectedUpc&&!visibleRecords.length&&<p className="table-empty">No inspection records for this UPC</p>}</div><aside className="reference-card"><h3>Quantity Reference</h3><dl><div><dt>Imported Reference</dt><dd>{carton.referenceQty??'No reference'}</dd></div><div><dt>Actual Inspected</dt><dd>{carton.inspectedQty}</dd></div><div><dt>Packed Quantity</dt><dd>{carton.sealedQty}</dd></div><div><dt>Difference</dt><dd className={difference===0?'match':difference===null?'':'mismatch'}>{difference===null?'No reference':difference===0?'Matched':difference>0?`Over ${difference}`:`Short ${Math.abs(difference)}`}</dd></div></dl><div className="mini-grades">{stats.map(([g,n])=><span key={g} className={`grade g${g}`}>{g} {n}</span>)}</div></aside></section></>;
}

function GradePanel({grade,rows,add,remove,update,addPhotos}:{grade:Grade;rows:DraftRow[];add:()=>void;remove:(id:number)=>void;update:(id:number,p:Partial<DraftRow>)=>void;addPhotos:(id:number,files:File[])=>void}){return <div className={`grade-panel panel-${grade}`}><div className="grade-panel-title"><span className={`grade g${grade}`}>{grade} Grade</span><button className="add-row" onClick={add} title={`Add a ${grade} grade row`}>＋</button></div><div className="draft-head"><span>Product Barcode</span><span>Quantity</span><span>Exception Reason</span><span>Images</span><span/></div>{rows.map((row,index)=><div className="draft-row" key={row.id}><input autoFocus={index===rows.length-1&&rows.length>1} value={row.barcode} onChange={e=>update(row.id,{barcode:e.target.value})} placeholder="Type or scan"/><input type="number" min="1" step="1" value={row.quantity} onChange={e=>update(row.id,{quantity:Number(e.target.value)})}/><input value={row.exceptionReason} onChange={e=>update(row.id,{exceptionReason:e.target.value})} placeholder="Optional"/>{row.recordId?<div className="drop-zone saved-photo-note">Existing images retained</div>:<label className="drop-zone"><input type="file" accept="image/png,image/jpeg" multiple onChange={e=>addPhotos(row.id,[...(e.target.files??[])])}/><span>{row.photos.length?row.photos.map((p,i)=><button type="button" key={`${p.name}-${i}`} onClick={e=>{e.preventDefault();update(row.id,{photos:row.photos.filter((_,x)=>x!==i)})}}>{p.name} ×</button>):'Choose images'}</span></label>}<button className="danger remove-row" onClick={()=>remove(row.id)}>Delete</button></div>)}</div>}

function BatchDialog({close,save}:{close:()=>void;save:(v:typeof emptyBatch)=>Promise<void>}) { const [v,setV]=useState(emptyBatch); return <div className="modal"><div className="dialog"><h2>New Inspection Batch</h2><div className="form-grid">{Object.entries(v).map(([k,val])=><label key={k}>{batchLabels[k]??k}<input type={typeof val==='number'?'number':k==='inspectionDate'?'date':'text'} value={val} onChange={e=>setV({...v,[k]:typeof val==='number'?Number(e.target.value):e.target.value})}/></label>)}</div><div className="dialog-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>save(v)}>Create</button></div></div></div> }
function DeleteBatchDialog({batch,close,remove}:{batch:Batch;close:()=>void;remove:()=>Promise<void>}){const [stage,setStage]=useState<1|2>(1);const [typed,setTyped]=useState('');const [busy,setBusy]=useState(false);if(stage===1)return <div className="modal delete-modal"><div className="dialog delete-warning"><div className="warning-symbol">!</div><h2>Delete Batch?</h2><p>Batch <strong>{batch.batchNo}</strong> and all of its cartons, inspection records, and images will be permanently deleted.</p><div className="dialog-actions"><button onClick={close}>Cancel</button><button className="danger-button" onClick={()=>setStage(2)}>Continue</button></div></div></div>;return <div className="modal delete-modal second-confirm"><div className="dialog delete-confirm"><h2>Final Confirmation</h2><p>Enter batch number <strong>{batch.batchNo}</strong> to confirm deletion:</p><input autoFocus value={typed} onChange={event=>setTyped(event.target.value)} placeholder="Enter the complete batch number"/><div className="dialog-actions"><button onClick={close}>Back</button><button className="danger-button" disabled={typed!==batch.batchNo||busy} onClick={async()=>{setBusy(true);try{await remove();}finally{setBusy(false)}}}>{busy?'Deleting…':'Delete Permanently'}</button></div></div></div>}
function CartonDialog({batchId,saved}:{batchId:number;saved:()=>Promise<void>}) { const [no,setNo]=useState('');const close=()=> (document.getElementById('new-carton') as HTMLDialogElement)?.close();return <dialog id="new-carton"><h2>Add Carton</h2><label>Cartons<input value={no} onChange={e=>setNo(e.target.value)}/></label><div className="dialog-actions"><button onClick={close}>Cancel</button><button className="primary" onClick={async()=>{await api.createCarton(batchId,no);setNo('');close();await saved();}}>Save</button></div></dialog> }
function ReportDialog({batch,cartons,close}:{batch:Batch;cartons:Carton[];close:()=>void}){const totals={A:cartons.reduce((n,c)=>n+c.gradeA,0),B:cartons.reduce((n,c)=>n+c.gradeB,0),C:cartons.reduce((n,c)=>n+c.gradeC,0),D:cartons.reduce((n,c)=>n+c.gradeD,0)};const total=totals.A+totals.B+totals.C+totals.D;return <div className="modal report-modal"><div className="dialog report-dialog"><div className="section-title"><div><h2>{batch.batchNo} Report</h2><p>Total inspected: {total}</p></div><button onClick={close}>Close</button></div><div className="report-grades">{(["A","B","C","D"] as Grade[]).map(grade=><div className={`report-grade panel-${grade}`} key={grade}><span className={`grade g${grade}`}>{grade} Grade</span><strong>{totals[grade]}</strong><small>{total?`${(totals[grade]/total*100).toFixed(1)}%`:'0.0%'}</small><i style={{width:`${total?totals[grade]/total*100:0}%`}}/></div>)}</div><h3>Carton Reconciliation</h3><div className="report-table"><table><thead><tr><th>Carton</th><th>Reference Quantity</th><th>Actual Quantity</th><th>Difference</th><th>Status</th></tr></thead><tbody>{cartons.map(c=>{const diff=c.referenceQty===null?null:c.inspectedQty-c.referenceQty;const state=c.inspectedQty===0?'Not inspected':diff===null?'No reference':diff===0?'Matched':diff>0?`Over ${diff}`:`Short ${Math.abs(diff)}`;return <tr key={c.id} className={diff===0?'match-row':diff===null?'':'mismatch-row'}><td>{c.cartonNo}</td><td>{c.referenceQty??'—'}</td><td>{c.inspectedQty}</td><td>{diff===null?'—':diff>0?`+${diff}`:diff}</td><td>{state}</td></tr>})}</tbody></table></div></div></div>}
function Notice({text,close}:{text:string;close:()=>void}) { return <div className="notice">{text}<button onClick={close}>×</button></div> }
const batchLabels:Record<string,string>={batchNo:'Batch Number',inspectionDate:'Inspection Date'};
const fileData=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)});
async function exportData(batchId:number){const outputDir=await open({directory:true,multiple:false,title:'Select Excel Export Folder'});if(!outputDir)return;const files=await api.exportBatch(batchId,outputDir);alert(`Export complete:\n${files.join('\n')}`)}
export default App;
